server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

ingester:
  max_block_duration: 5m

compactor:
  compaction:
    # Set retention to 2 weeks (336 hours)
    block_retention: 336h

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/blocks
    block:
      bloom_filter_false_positive: 0.05